package sourcedb;
// Generated Oct 17, 2021 1:29:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Director generated by hbm2java
 */
@Entity
@Table(name="director"
    ,catalog="peliculas"
)
public class Director  implements java.io.Serializable {


     private Integer iddirector;
     private String nombre;
     private String nacionalidad;
     private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

    public Director() {
    }

	
    public Director(String nombre, String nacionalidad) {
        this.nombre = nombre;
        this.nacionalidad = nacionalidad;
    }
    public Director(String nombre, String nacionalidad, Set<Pelicula> peliculas) {
       this.nombre = nombre;
       this.nacionalidad = nacionalidad;
       this.peliculas = peliculas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddirector", unique=true, nullable=false)
    public Integer getIddirector() {
        return this.iddirector;
    }
    
    public void setIddirector(Integer iddirector) {
        this.iddirector = iddirector;
    }

    
    @Column(name="nombre", nullable=false, length=80)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="nacionalidad", nullable=false, length=30)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="director")
    public Set<Pelicula> getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set<Pelicula> peliculas) {
        this.peliculas = peliculas;
    }

    @Override
    public String toString() {
        return this.nombre;
    }




}


