package sourcedb;
// Generated Oct 17, 2021 1:29:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genero generated by hbm2java
 */
@Entity
@Table(name="genero"
    ,catalog="peliculas"
)
public class Genero  implements java.io.Serializable {


     private Integer idgenero;
     private String generopelicula;
     private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

    public Genero() {
    }

	
    public Genero(String generopelicula) {
        this.generopelicula = generopelicula;
    }
    public Genero(String generopelicula, Set<Pelicula> peliculas) {
       this.generopelicula = generopelicula;
       this.peliculas = peliculas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idgenero", unique=true, nullable=false)
    public Integer getIdgenero() {
        return this.idgenero;
    }
    
    public void setIdgenero(Integer idgenero) {
        this.idgenero = idgenero;
    }

    
    @Column(name="generopelicula", nullable=false, length=30)
    public String getGeneropelicula() {
        return this.generopelicula;
    }
    
    public void setGeneropelicula(String generopelicula) {
        this.generopelicula = generopelicula;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="genero")
    public Set<Pelicula> getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set<Pelicula> peliculas) {
        this.peliculas = peliculas;
    }

    @Override
    public String toString() {
        return this.generopelicula;
    }




}


