package sourcedb;
// Generated Oct 17, 2021 1:29:52 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pelicula generated by hbm2java
 */
@Entity
@Table(name="pelicula"
    ,catalog="peliculas"
)
public class Pelicula  implements java.io.Serializable {


     private int idpelicula;
     private Director director;
     private Genero genero;
     private String titulopelicula;
     private String descripcion;
     private String imgpelicula;
     private String titulooriginal;
     private String duracion;

    public Pelicula() {
    }

	
    public Pelicula(int idpelicula, Genero genero, String titulopelicula, String descripcion, String imgpelicula, String titulooriginal, String duracion) {
        this.idpelicula = idpelicula;
        this.genero = genero;
        this.titulopelicula = titulopelicula;
        this.descripcion = descripcion;
        this.imgpelicula = imgpelicula;
        this.titulooriginal = titulooriginal;
        this.duracion = duracion;
    }
    public Pelicula(int idpelicula, Director director, Genero genero, String titulopelicula, String descripcion, String imgpelicula, String titulooriginal, String duracion) {
       this.idpelicula = idpelicula;
       this.director = director;
       this.genero = genero;
       this.titulopelicula = titulopelicula;
       this.descripcion = descripcion;
       this.imgpelicula = imgpelicula;
       this.titulooriginal = titulooriginal;
       this.duracion = duracion;
    }
   
     @Id 

    
    @Column(name="idpelicula", unique=true, nullable=false)
    public int getIdpelicula() {
        return this.idpelicula;
    }
    
    public void setIdpelicula(int idpelicula) {
        this.idpelicula = idpelicula;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="iddirector")
    public Director getDirector() {
        return this.director;
    }
    
    public void setDirector(Director director) {
        this.director = director;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idgenero", nullable=false)
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }

    
    @Column(name="titulopelicula", nullable=false, length=120)
    public String getTitulopelicula() {
        return this.titulopelicula;
    }
    
    public void setTitulopelicula(String titulopelicula) {
        this.titulopelicula = titulopelicula;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="imgpelicula", nullable=false, length=200)
    public String getImgpelicula() {
        return this.imgpelicula;
    }
    
    public void setImgpelicula(String imgpelicula) {
        this.imgpelicula = imgpelicula;
    }

    @Override
    public String toString() {
        return this.titulopelicula;
    }

    
    @Column(name="titulooriginal", nullable=false, length=60)
    public String getTitulooriginal() {
        return this.titulooriginal;
    }
    
    public void setTitulooriginal(String titulooriginal) {
        this.titulooriginal = titulooriginal;
    }

    
    @Column(name="duracion", nullable=false, length=25)
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }




}


