/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud3;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sourcedb.Director;
import sourcedb.Genero;
import sourcedb.Pelicula;

/**
 *
 * @author Shy
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    List<Pelicula> ListaPeliculas;
    List<Genero> ListaGeneros;
    List<Director> ListaDirectores;
    Peliculas Pelis = new Peliculas();
    
    
    public Principal() {
        initComponents();
        ListaPeliculas = Pelis.ObtenerPelicula();
        ListaGeneros = Pelis.ObtenerGenero();
        ListaDirectores = Pelis.ObtenerDirector();
        
        this.ListarDirectoresGeneros();
        this.ListarPeliculas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboDirectores = new javax.swing.JComboBox<>();
        BotonGuardar = new javax.swing.JButton();
        BotonAgregarDirector = new javax.swing.JButton();
        ComboGeneros = new javax.swing.JComboBox<>();
        TextTitulo = new javax.swing.JTextField();
        TextTituloOriginal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextDescripcion = new javax.swing.JTextArea();
        TextDuracion = new javax.swing.JTextField();
        ComboPelicula = new javax.swing.JComboBox<>();
        BotonModificar = new javax.swing.JButton();
        BotonAgregarGenero = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        LabelTitulo = new javax.swing.JLabel();
        LabelDirector = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonAgregarDirector.setText("Agregar Director");
        BotonAgregarDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarDirectorActionPerformed(evt);
            }
        });

        TextTitulo.setText("Titulo");
        TextTitulo.setToolTipText("Titulo");

        TextTituloOriginal.setText("Titulo Original");
        TextTituloOriginal.setToolTipText("Titulo Original");

        TextDescripcion.setColumns(20);
        TextDescripcion.setLineWrap(true);
        TextDescripcion.setRows(5);
        TextDescripcion.setText("Descripción...");
        TextDescripcion.setToolTipText("Descripción de la pelicula");
        TextDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(TextDescripcion);

        TextDuracion.setText("Duración (min)");
        TextDuracion.setToolTipText("Duración (min)");

        ComboPelicula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboPeliculaItemStateChanged(evt);
            }
        });

        BotonModificar.setText("Modificar Pelicula");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        BotonAgregarGenero.setText("Agregar Genero");
        BotonAgregarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarGeneroActionPerformed(evt);
            }
        });

        LabelTitulo.setText("...");

        LabelDirector.setText("...");

        jLabel3.setText("Titulo");

        jLabel4.setText("Director");

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("CRUD - Hibernate | DSE104 | PM170641 - MD170149 - RM170126");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonAgregarDirector)
                .addGap(26, 26, 26)
                .addComponent(BotonAgregarGenero)
                .addGap(220, 220, 220))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextTituloOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(ComboGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ComboDirectores, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BotonModificar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(BotonGuardar))
                            .addComponent(ComboPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                            .addComponent(jSeparator2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboDirectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextTituloOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(BotonGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(ComboPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonModificar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelDirector))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregarGenero)
                    .addComponent(BotonAgregarDirector))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListarDirectoresGeneros() {
        ListaDirectores = Pelis.ObtenerDirector();
        
        ComboDirectores.removeAllItems();
        for (int i = 0; i < ListaDirectores.size(); i++) {

            ComboDirectores.addItem(ListaDirectores.get(i));
        }
        ComboGeneros.removeAllItems();
        for (int i = 0; i < ListaGeneros.size(); i++) {
            
            ComboGeneros.addItem(ListaGeneros.get(i));
        }
    }
    
    private void ListarPeliculas(){
        ListaPeliculas = Pelis.ObtenerPelicula();
        ComboPelicula.removeAllItems();
        for (int i = 0; i < ListaPeliculas.size(); i++) {

            ComboPelicula.addItem(ListaPeliculas.get(i));
        }
    }
    
    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
        try {
        Pelis.InsertarPelicula(TextTitulo.getText(), TextTituloOriginal.getText(), TextDuracion.getText(), TextDescripcion.getText(), (Director)ComboDirectores.getSelectedItem(), (Genero)ComboGeneros.getSelectedItem());
            JOptionPane.showMessageDialog(this, "Agregado con Exito");
        }catch(Error err){
            JOptionPane.showMessageDialog(this, err);
        }
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonAgregarDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarDirectorActionPerformed
        // TODO add your handling code here:
        
        ModDirectores FrameDirectores = new ModDirectores();
        FrameDirectores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAgregarDirectorActionPerformed

    private void BotonAgregarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarGeneroActionPerformed
        // TODO add your handling code here:
        ModGeneros FrameGeneros = new ModGeneros();
        FrameGeneros.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAgregarGeneroActionPerformed

    private void ComboPeliculaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboPeliculaItemStateChanged
        // TODO add your handling code here:
        Pelicula pelicula = (Pelicula)ComboPelicula.getSelectedItem();
        
        LabelTitulo.setText(pelicula.getTitulopelicula());
        LabelDirector.setText(pelicula.getDirector().toString());
    }//GEN-LAST:event_ComboPeliculaItemStateChanged

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        // TODO add your handling code here:
        Pelicula pelicula = (Pelicula)ComboPelicula.getSelectedItem();
        ModPelicula FramePelicula = new ModPelicula();
        
        FramePelicula.setVisible(true);
        FramePelicula.AsignarValores(pelicula);
        
        this.dispose();
        
    }//GEN-LAST:event_BotonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarDirector;
    private javax.swing.JButton BotonAgregarGenero;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JComboBox<Director> ComboDirectores;
    private javax.swing.JComboBox<Genero> ComboGeneros;
    private javax.swing.JComboBox<Pelicula> ComboPelicula;
    private javax.swing.JLabel LabelDirector;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JTextArea TextDescripcion;
    private javax.swing.JTextField TextDuracion;
    private javax.swing.JTextField TextTitulo;
    private javax.swing.JTextField TextTituloOriginal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}



